include:
  - ./traefik/docker-compose.yaml
  - ./docker_registry/docker-compose.yaml
  - ./jenkins/docker-compose.yaml
  - ./monitoring/docker-compose.yml
  - ./postgres/docker-compose.yaml

networks:
  proxy:
    name: proxy
    driver: bridge
