services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /srv/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - proxy
    restart: unless-stopped
    # порт 9090 не пробрасываем наружу — он доступен только из сети monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000" # только этот доступен снаружи
    volumes:
      - grafana-storage:/var/lib/grafana
      - /srv/docker/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - proxy
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.chiz.work.gd`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"
    restart: unless-stopped

  loki:
    image: grafana/loki
    networks:
      - proxy
    volumes:
      - /srv/docker/loki/config.yaml:/etc/loki/config.yaml:ro
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    networks:
      - proxy
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - /srv/docker/promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/log:/var/log:ro

      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /var/lib/containerd:/var/lib/containerd:ro
      
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped


  tempo:
    image: grafana/tempo
    networks:
      - proxy
    volumes:
      - /srv/docker/tempo/tempo-config.yaml:/etc/tempo-config.yaml:ro
    command: ["--config.file=/etc/tempo-config.yaml"]
    restart: unless-stopped


  node_exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node_exporter
    restart: unless-stopped
    networks:
      - proxy
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring-cadvisor
    restart: unless-stopped
    networks:
      - proxy
    privileged: true
    command:
      - "--housekeeping_interval=15s"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8083:8080"

volumes:
  grafana-storage:

networks:
  proxy:
    driver: bridge
    name: proxy
