services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - proxy
    # порт 9090 не пробрасываем наружу — он доступен только из сети monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  # только этот доступен снаружи
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - proxy
    depends_on:
      - prometheus
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.chiz.work.gd`)"
    - "traefik.http.routers.grafana.entrypoints=websecure"
    - "traefik.http.routers.grafana.tls=true"
    - "traefik.http.routers.grafana.tls.certresolver=le"

  loki:
    image: grafana/loki
    networks:
      - proxy
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro


  promtail:
    image: grafana/promtail
    networks:
      - proxy
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/log/nestjs:/var/log/nestjs:ro
    command: -config.file=/etc/promtail/config.yaml

  tempo:
    image: grafana/tempo
    networks:
      - proxy
    volumes:
      - ./tempo/tempo-config.yaml:/etc/tempo-config.yaml:ro
    command: ["--config.file=/etc/tempo-config.yaml"]

  node_exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node_exporter
    restart: unless-stopped
    networks:
      - proxy
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring-cadvisor
    restart: unless-stopped
    networks:
      - proxy
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8083:8080"

volumes:
  grafana-storage:

networks:
  proxy:
    driver: bridge
    name: proxy
