services:
  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${X_HOST_DOMAIN:-chiz.reg.gd}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  whoami-api:
    image: "traefik/whoami"
    networks:
      - proxy
    container_name: "whoami-api"
    environment:
      - WHOAMI_NAME=API Service
    labels:
      - "traefik.enable=true"
      # Path-based routing
      - "traefik.http.routers.whoami-api.rule=Host(`${X_HOST_DOMAIN:-chiz.reg.gd}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.whoami-api.entrypoints=web"

networks:
  proxy:
    name: proxy
