global:
  scrape_interval: 15s

scrape_configs:
  # ───────────── Traefik ─────────────
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8082"] # если ты используешь entrypoint metrics на 8082

  # ───────────── PostgreSQL ─────────────
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  # ───────────── Node Exporter ─────────────
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['monitoring-node_exporter:9100']
  # ───────────── cAdvisor ─────────────
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitoring-cadvisor:8080']

  
  - job_name: 'promtail'
    static_configs:
      - targets: ['monitoring-promtail:9080']