global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs-api'
    static_configs:
      - targets: ['host.docker.internal:3000']



  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']