services:
  postgres:
    container_name: postgres_db
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_DB: "postgress122"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "5432:5432"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres123@postgres:5432/?sslmode=disable"

    networks:
      - proxy
    depends_on:
      - postgres

volumes:
  db-data:

networks:
  proxy:
    driver: bridge
    name: proxy
