services:
  postgres:
    container_name: postgres_db
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_DB: "postgress"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /srv/docker/postgres/db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "5432:5432"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres_db:5432/postgress?sslmode=disable"

    networks:
      - proxy
    depends_on:
      - postgres

volumes:
  db-data:
